### ISSUE TITLE
Incomplete neuron version

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/bbp-nixpkgs#403]
When I load the nix neuron module (nix/hpc/neuron/7.5-201707 on CSCS viz), it shows me the following version:

NEURON -- VERSION 7.5 master (NO_GIT) 201707

When I do the same in a git version of neuron compiled the normal way, I get something like:
NEURON -- VERSION 7.5 (1469+:60a58922f20e+) 2016-10-24

As you can see the date format is different and we get a reference to the git hash.

For provenance we need to be able to let scripts save the git hash of the exact neuron version. 
Also BGLibPy depends on the date format, to switch between certain functionality (that only works in newer versions of Neuron).

Could you make sure that the nix neuron package picks up the correct git hash and date ?

@elisabettai and @christian-oreilly pointed me to this problem.

**Comment by adevress** [comment]
Hi Werner,

It is rather trivial to do, I will add that for the next release.

However, please consider we are using Neuron from the github repository, not from Mercurial... The Hash itself will be the git hash, not the mercurial hash.

Adrien

**Comment by adevress** [comment]
@wvangeit  It shoudl be fixed Werner. Could you give a try on lugano viz cluster and let me know ?

**Comment by adevress** [comment]
@wvangeit Note : We are also proceeding to the decoupling neuron <-> neurodamus like discussed before, you might get a slight module name change and need to load both neuron and neurodamus and

**Comment by wvangeit** [comment]
I tried, but I get:
>>> import neuron
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/p4skhrd880j2v6vp0cww76pl6852r241-generated-env-module-neuron/lib/python2.7/site-packages/neuron/__init__.py", line 112, in <module>
    exec("import neuron.hoc%d%d as hoc" % (sys.version_info[0], sys.version_info[1]))
  File "<string>", line 1, in <module>
ImportError: No module named hoc27

If I
 module load nix/python/2.7-full
of 
 module load nix/python/2.7-light

I get:
ImportError: No module named site

**Comment by adevress** [comment]
I don't get that on my session.

Could you try with a module purge before, cleaning any PYTHON* env and cleaning your LD_LIBRARY_PATH ?

**Comment by adevress** [comment]
$ module purge
$ module load nix/hpc/neuron nix/python/2.7-full
]$ python 
Python 2.7.11 (default, Jan 01 1970, 00:00:01) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import neuron
NEURON -- VERSION 7.5 master (ee80eb94d3f34e86299a0498b5c1b87f8e8bcaa3) 2017-08-06
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2016
See http://neuron.yale.edu/neuron/credits

>>>

**Comment by wvangeit** [comment]
Ok, it was the LD_LIBRARY_PATH. It seems the module nix/python module doesn't work when the RH software collection python was loaded before.

The neuron version is now set correctly indeed

**Comment by adevress** [comment]
> Ok, it was the LD_LIBRARY_PATH. It seems the module nix/python module doesn't work when the RH software collection python was loaded before.

It makes sense, the nix modules use DT_RUNPATH, LD_LIBRARY_PATH overwrite that.

Adrien

**Comment by wvangeit** [comment]
Wouldn't it make sense for nix to use DT_RPATH instead of DT_RUNPATH ? That seems to take precedence over LD_LIBRARY_PATH

**Comment by adevress** [comment]
> Wouldn't it make sense for nix to use DT_RPATH instead of DT_RUNPATH 

In fact no, because the problem with RPATH is that it is not overwritable, which cause also problem when you want to overwrite it for good reasons ( like adding some plugins in the path ).

Most operating system tags RPATH as "deprecated" in favor of RUNPATH for this reason

**Comment by wvangeit** [comment]
Maybe then it would make sense to let the python module add it's lib path to the LD_LIBRARY_PATH ?

**Comment by adevress** [comment]
Yes it might be a good idea or at least checking it, because a normal nix usage normally requires nothing in LD_LIBRARY_PATH, the libpath is entirely contains in the binaries itself.

**Comment by adevress** [comment]
Ok I close the ticket if it is working for you, don't hesitate to re-open if you encounter anything
