### ISSUE TITLE
Nrn patch breaks reproducibility

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/bbp-nixpkgs#502]
This patch:
https://github.com/BlueBrain/bbp-nixpkgs/blob/cd3d1b9b05ec8e93eb7e4db02897cdd1c53bcfda/bbp/hpc/neuron/nrn.patch#L18
breaks the reproducibility of the results of this channel.

Is this change there because of CoreNEURON ?

Could we fix this in some way, because if we install NEURON using nix on other machines it might break the reproducibility of people's scripts.

E.g. the tutorials we are presenting at conferences use this channel.

**Comment by pramodskumbhar** [comment]
yes, this was added for coreneuron. But as coreneuron is not actively used by others yet, we can skip this patch for time being.

**Comment by adevress** [comment]
Hi Werner,

Thx Pramod for the precisions.

I will update it to the last version and disable the patch

**Comment by adevress** [comment]
See #503

**Comment by wvangeit** [comment]
I assume this can be closed ?
