### ISSUE TITLE
Provides pyapache Python package

### ISSUE THREAD

**Issue by tristan0x** [BlueBrain/bbp-nixpkgs#625]
@arsenius7 needs this package to use `feather-format` Python package.
Here are some hints to build the Nix recipe ... https://arrow.apache.org/docs/python/development.html#development

**Comment by arsenius7** [comment]
Hi, @tristan0x.
Would you be able to look into that?
It would help a lot, because frankly I don't have a clear understanding how to apply the instructions you've provided above in the context of Nix build.
Thanks.

**Comment by jdcourcol** [comment]
@wizmer can you follow up on that with @tristan0x  ?

**Comment by christian-oreilly** [comment]
Any progress on this issue? It is blocking the integration of the Projectionizer to our modeling pipeline... What is the current ETA?

**Comment by arsenius7** [comment]
Thanks for the heads up, Tristan.

I guess `pyarrow` was not available in Nix environment back when the ticket was created; and I have not tracked it since then.

Looks like we have what we need for packing `Projectionizer` now, but let me take a look in the next couple of days.

**Comment by arsenius7** [comment]
I guess #967 commit from @wizmer confirms that we can use `pyarrow` package provided.
Thanks.

**Comment by jdcourcol** [comment]
Is there any good reason to leave that ticket open ?
