### ISSUE TITLE
fetchBBPDevpi and firewall maddness

### ISSUE THREAD

**Issue by adevress** [BlueBrain/bbp-nixpkgs#642]
ping @arsenius7 

I just found out a big issue with fetchBBPDevpi in fact.

 - bbpcode where the package where coming from before is open to the internet with authentication
 - The devpi server is not for security reason

This is a major issue because it makes the installation on every site outside BBP (All HBP machines) fails and that is not acceptable.

We will need to fix that in some way.

**Comment by arsenius7** [comment]
Hi Adrien.

Sorry for a late reply, I was out of the office end of last week.
I don't see why should we prevent read-only authenticated access to devpi if we give such an access to bbpcode, but I guess it would take some time to set it up.

Meanwhile I can rollback fetchBBPDevpi usage back to fetchgitPrivate.

**Comment by adevress** [comment]
Hi Arseny,

That might be more tricky than that. bbpcode is accessed through SSH and open like that. I don't think devpi supports SSH.

Relying on HTTP + password for devpi implies to put your user + password in a netrc file somewhere, which you probably don't want the users to do.

**Comment by arsenius7** [comment]
ergh, OK, I see. :)
fetchgitPrivate has a problem with BGLibPy versioning though (it is installed as '0+unknown').
I'll look into that and make a PR rolling back fetchBBPDevpi (until better times).

**Comment by adevress** [comment]
thx
