### ISSUE TITLE
Pickleshare version BluePyOpt

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/bbp-nixpkgs#828]
I just saw this line:
https://github.com/BlueBrain/bbp-nixpkgs/blob/master/bbp/nse/bluepyopt/default.nix#L20
It seems it's there to pin the version of pickleshare to a very old version.

Could you upgrade the pickleshare version to >= 0.7.3

The reason this pickleversion of >=0.7.3 is required in bluepyopt is because of this PR:
https://github.com/pickleshare/pickleshare/pull/23
Older versions can create a race condition causing optimisations to fail from time to time in a stochastic way.

**Comment by tristan0x** [comment]
Hello @wvangeit 
PickleShare is 0.7.4 in Nix recipes

```
nix-shell -p pythonPackages.pickleshare --command python
Python 2.7.14 (default, Sep 16 2017, 17:49:51) 
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickleshare
>>> pickleshare.__version__
'0.7.4'
```

Can you submit a pull-request without the `preConfigure`?
