### ISSUE TITLE
Update pandas

### ISSUE THREAD

**Issue by wizmer** [BlueBrain/bbp-nixpkgs#965]
Hi @tristan0x,

For one of my package I need pandas 0.23. I could override the pandas default.nix by creating a new one in the `patches` folder but I have seen that `master` branch of `nix-pkgs` already have it so we could also upgrade the nix-pkgs submodule. What do you think ?

Thanks

**Comment by tristan0x** [comment]
Hello @wizmer 
Yes, you can cherry-pick the change from NixOS/nix-pkgs to adevress/nixpkgs-base master branch.

**Comment by wizmer** [comment]
Thanks. I have created a PR here: https://github.com/adevress/nixpkgs-base/pull/3
Do you have an estimate when does the master branch of nixpkgs-base will cascade into bbp-nixpkgs ?

**Comment by tristan0x** [comment]
I am testing your PR on `nixpkgs-base` by building pandas package with both Python 2 and Python 3. I will merge if ok.

**Comment by tristan0x** [comment]
Fixed in #969
